[package]
name = "voting_tools_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

color-eyre = "0.6"  # error handling
clap = { version = "3.2", features = ["derive"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1"

microtype = { version = "0.7.1", features = ["serde"] }

diesel = { version = "1.4", features = ["postgres", "r2d2"] }
tokio = { version = "1", features = ["rt"] }

