[package]
name = "voting_tools_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

color-eyre = "0.6"  # error handling
clap = { version = "3.2", features = ["derive"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1"

microtype = { version = "0.7.5", features = ["serde"] }

tokio = { version = "1", features = ["full"] }
futures = "0.3"

tokio-postgres = { version = "0.7", features = ["with-serde_json-1"]}
bb8 = "0.8"
bb8-postgres = "0.8"

hex = "0.4"

tracing = "0.1"
tracing-subscriber = "0.3"
rust_decimal = { version = "1.26", features = ["serde", "db-postgres"] }

cardano-serialization-lib = "11.0.0"

[dev-dependencies]
proptest = { git = "https://github.com/input-output-hk/proptest" }
test-strategy = "0.2"
reqwest = { version = "0.11", features = ["rustls-tls", "blocking", "json"], default-features = false }
serial_test = "0.9"
tempdir = "0.3"
tracing-test = "0.2"

[features]
all_tests = ["network_tests"]
network_tests = []
